version: '3.9'

services:
  nginx:
    container_name: "nginx"
    image: "app_nginx"
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile  
    volumes:
      - "./app:/var/www/html:rw,Z"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d:ro,Z"
    ports:
      - "${NGINX_EXPOSED_PORT}:80"
    depends_on:
      - mariadb
      - pma
      # - mailhog
      - php-fpm
    networks:
      - no-internet
      - internet
      
  php-fpm:
    container_name: "php-fpm"
    image: "app_php_fpm"
    build:
      context: ./docker
      dockerfile: php-fpm/${PHP_VERSION}/Dockerfile
      args:
        PHP_INI_DIR: "${PHP_INI_DIR}"
        PHP_VERSION: "${PHP_VERSION}"
    environment:
        PHP_IDE_CONFIG: serverName=${PHPSTORM_DEBUG_SERVER_NAME}
        PHP_OPCACHE_ENABLED: ${PHP_OPCACHE_ENABLED}
        PHP_OPCACHE_REVALIDATE_FREQ: ${PHP_OPCACHE_REVALIDATE_FREQ}
        PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
        PHP_OPCACHE_MAX_ACCELERATED_FILES: ${PHP_OPCACHE_MAX_ACCELERATED_FILES}
        PHP_OPCACHE_MEMORY_CONSUMPTION: ${PHP_OPCACHE_MEMORY_CONSUMPTION}
        PHP_OPCACHE_MAX_WASTED_PERCENTAGE: ${PHP_OPCACHE_MAX_WASTED_PERCENTAGE}
        PHP_OPCACHE_INTERNED_STRINGS_BUFFER: ${PHP_OPCACHE_INTERNED_STRINGS_BUFFER}
        PHP_OPCACHE_FAST_SHUTDOWN: ${PHP_OPCACHE_FAST_SHUTDOWN}
        PHP_JIT_BUFFER_SIZE: ${PHP_JIT_BUFFER_SIZE}
        PHP_JIT_PARAMS: ${PHP_JIT_PARAMS}
    volumes:
      - "./app:/var/www/html:rw,Z"
      - "./docker/php-fpm/conf.d/xdebug.ini:${PHP_INI_DIR}/conf.d/xdebug.ini:ro,Z"
      - "./docker/php-fpm/${PHP_VERSION}/opcache.ini:${PHP_INI_DIR}/conf.d/opcache.ini:ro,Z"
      - "./docker/php-fpm/${PHP_VERSION}/php.ini:${PHP_INI_DIR}/php.ini:ro,Z"
    networks:
      - no-internet
      - internet

  mariadb:
    container_name: "mariadb"
    image: mariadb:latest
    volumes:
      - "./db:/var/lib/mysql:rw,Z"
      - "./docker/mariadb/conf.d/skadate.cnf:/etc/mysql/conf.d/skadate.cnf:ro,Z"
    ports:
      - "${MYSQL_EXPOSED_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - no-internet
      - internet

  pma:
    container_name: "pma"
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mariadb
    volumes:
      - "./docker/pma/etc/config.user.inc.php:/etc/pma/config.user.inc.php:ro,Z"
    environment:
      PMA_HOST: "mariadb"
      PMA_PORT: 3306
      PMA_VERBOSE: "App develepoment database"
      PMA_ARBITRARY: 0
      PMA_ABSOLUTE_URI: "http://localhost/pma/"
      UPLOAD_LIMIT: "${PMA_UPLOAD_LIMIT}"
      MEMORY_LIMIT: "${PMA_MEMORY_LIMIT}"
    networks:
      - no-internet

  # mailhog:
  #   container_name: "mailhog"
  #   image: "skadate_mailhog"
  #   build:
  #       context: ./docker
  #       dockerfile: mailhog/Dockerfile
  #   logging:
  #     driver: 'none'
  #   ports:
  #     - "${MAILHOG_SMTP_EXPOSED_PORT}:1025"
  #   networks:
  #     - no-internet
  #     - internet

  php-cli:
    container_name: "php-cli"
    image: "app_php_cli"
    command: ["sleep", "infinity"]
    build:
      context: ./docker
      dockerfile: php-cli/${PHP_VERSION}/Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION}"
    networks:
      - no-internet
      - internet

  # redis:
  #   image: redis:alpine
  #   hostname: redis
  #   container_name: redis
  #   restart: always
  #   networks:
  #     - no-internet
  #     - internet

  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: ghcr.io/joeferner/redis-commander:latest
  #   restart: always
  #   depends_on:
  #     - redis
  #   environment:
  #   - REDIS_HOSTS=skadate:redis:6379
  #   networks:
  #     - no-internet
  #     - internet

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    internal: false
